name:                surreal-db
version:             0.1.1.0
github:              "farzadbekran/surreal-db"
license:             BSD3
author:              "Farzad Bekran"
maintainer:          "farzadbekran@gmail.com"
copyright:           "2025 Farzad Bekran"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/farzadbekran/surreal-db#readme>

dependencies:
- base >= 4.7 && < 5
- classy-prelude
- websockets
- aeson
- text
- network
- mtl
- transformers
- containers
- bytestring
- Decimal
- row-types
- row-types-aeson
- first-class-families
- time
- iso8601-time
- megaparsec
- parser-combinators
- template-haskell
- profunctors
- vector
- exceptions
- effectful
- effectful-core
- effectful-th
- effectful-plugin
- uuid

ghc-options:
- -Wall
- -Werror
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fplugin=Effectful.Plugin

default-extensions:
- OverloadedLabels
- OverloadedStrings
- NoImplicitPrelude
- FlexibleContexts
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- TypeOperators

library:
  source-dirs: src

tests:
  surreal-db-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - surreal-db
